import type { Metadata } from "next";
import { Provider } from "site/components/ui/provider";
import "./globals.css";
import { AnimatePresence } from "framer-motion";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider><AnimatePresence>{children}</AnimatePresence></Provider>
      </body>
    </html>
  );
}
