name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: site/package-lock.json

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            site/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('site/package-lock.json') }}-${{ hashFiles('site/**/*.[jt]s', 'site/**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('site/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci
        working-directory: site

      - name: Build with Next.js
        run: npx --no-install next build
        working-directory: site

      - name: Export static site
        run: npx --no-install next build && mv out ../out
        working-directory: site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
